# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       qmlgallery

# >> macros
# << macros

Summary:    Photo Gallery for Nemo
Version:    0.1.0
Release:    1
Group:      Applications/System
License:    BSD
URL:        https://github.com/nemomobile/qmlgallery
Source0:    %{name}-%{version}.tar.bz2
Source100:  qmlgallery.yaml
Requires:   qt-components-qt5
Requires:   qt5-qtdeclarative-import-multimedia
Requires:   nemo-qml-plugin-thumbnailer-qt5
Requires:   qt5-qtdocgallery
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(qdeclarative5-boostable)
BuildRequires:  pkgconfig(libresourceqt5)
BuildRequires:  desktop-file-utils
Provides:   meego-handset-video > 0.2.5
Obsoletes:   meego-handset-video <= 0.2.5

%description
Photo Gallery application using Qt Quick for Nemo Mobile.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}/qmlgallery
%{_datadir}/applications/qmlgallery.desktop
%{_libdir}/qt5/qml/org/nemomobile/qmlgallery/*
# >> files
# << files
